# Generated by Django 4.2.3 on 2023-08-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='prompt',
            new_name='user_message',
        ),
    ]
